"""add phone number and device token to users table

Revision ID: a8778f4ebb14
Revises: e3eb2eda86a4
Create Date: 2026-09-18 22:25:45.137269

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8778f4ebb14"
down_revision: str | Sequence[str] | None = "e3eb2eda86a4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("phone_number", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "users", sa.Column("device_token", sa.String(length=255), nullable=True)
    )
    op.create_index(
        op.f("ix_users_device_token"), "users", ["device_token"], unique=False
    )
    op.create_index(
        op.f("ix_users_phone_number"), "users", ["phone_number"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_phone_number"), table_name="users")
    op.drop_index(op.f("ix_users_device_token"), table_name="users")
    op.drop_column("users", "device_token")
    op.drop_column("users", "phone_number")
    # ### end Alembic commands ###
